FROM alpine:3.18@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978 as otelc_curl
RUN apk --update add curl

FROM otel/opentelemetry-collector:latest@sha256:fdc734899d92d3a7d04a586a4eff5778d28e55594ffb2350ae1e35bc101b4427

COPY --from=otelc_curl / /

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
USER 0
RUN chmod o+r /etc/otel-collector-config.yaml
USER nobody
