name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: github.repository == 'envoyproxy/envoy'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@0efb1d1d84fc9633afcdaad14c485cbbc90ef46c
